# Generated by Django 4.0.6 on 2023-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20220608_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='nfcId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
