# Generated by Django 4.0.6 on 2023-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_nfccheck_respite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccheck',
            name='respite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
