# Generated by Django 4.2 on 2023-05-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_nfccheck_respite'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_book',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='accept_people', to='accounts.book'),
            preserve_default=False,
        ),
    ]
