# Generated by Django 4.2 on 2023-05-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_accept_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept_book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='accept_book',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='accept_book',
            name='key',
        ),
    ]
