# Generated by Django 4.2 on 2023-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_accept_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_book',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name='Муаллифи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accept_book',
            name='book_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Kitob nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accept_book',
            name='key',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
