# Generated by Django 4.0.6 on 2023-05-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_accept_book_author_accept_book_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accept_book',
            name='book',
        ),
    ]
