# Generated by Django 4.0.6 on 2024-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_accept_book_key_alter_book_key_alter_check_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='passCode',
            field=models.IntegerField(default=1234, max_length=4),
        ),
    ]
