# Generated by Django 4.0.6 on 2024-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_students_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_book',
            name='key',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='passCode',
            field=models.IntegerField(default=1234),
        ),
    ]
