# Generated by Django 4.0.6 on 2023-03-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
